### ISSUE TITLE
Feature idea: holding state in URL

### ISSUE THREAD

**Issue by golddranks** [akx/gradient#2]
Convenient to share gradients with colleagues via links.

**Comment by akx** [comment]
Implemented in a manual way in https://github.com/akx/gradient/commit/0d7fba8bdbdd282a9ece55e31f2d7afcb346c3e4 -- there's now an option to share a "compressed" URL e.g. https://akx.github.io/gradient/?s=AaEorlIkL2P8sxUPrwCTm0-aQEVqAAAAAAA
