### ISSUE TITLE
UI annoyance: too much precision in decimal numbers

### ISSUE THREAD

**Issue by golddranks** [akx/gradient#4]
Maximum precision needed for colour values would be 1/255 = 0.0039 ≈ 0.001. I think that the position would be also fine with that precision.

**Comment by akx** [comment]
I semi-disagree: this tool could well be used in a non-8-bit context (which is the reason RGBA values are internally stored as floats 0..1)...

**Comment by golddranks** [comment]
Good point. I'll close this.
